### PR TITLE
add caps:c

### PR DESCRIPTION
**Pull request by HookedBehemoth**

### CODE REVIEW

**Comment by yellows8** [comment]
rebase?

**Comment by HookedBehemoth** [comment]
Huh? Didn't I pull in the latest changes from master?

**Comment by yellows8** [comment]
"This branch cannot be rebased due to conflicts ..."

**Comment by HookedBehemoth** [comment]
Not sure what I did wrong or what I'm supposed to do there. :sweat_smile:

**Comment by HookedBehemoth** [comment]
sigh

**Comment by HookedBehemoth** [comment]
sigh

**Pull request closed without merging**
