### PR TITLE
[irs] Name image transfer config variables

### PR DESCRIPTION
**Pull request by CTCaer**
As requested.

### CODE REVIEW

**Comment by plutooo** [comment]
Can you follow coding style so members are like_this?

Also please avoid naming the member in the comment, so instead of:
// exposure controls the sensor's exposure time in microseconds.
You can put:
// The sensor's exposure time in microseconds.

**Comment by fincs** [comment]
Docu comment should be `type field_name; ///< The description of the field.`

**Comment by CTCaer** [comment]
Changed the style as requested.

What about the comment that explains the default config settings in irsGetDefaultImageTransferProcessorConfig()?

**Comment by yellows8** [comment]
That comment should be added to irs.h.

Can you add info for what values for each field does?

**Comment by CTCaer** [comment]
Like this?
```
typedef struct {
    u64 exposure;     ///< IR Sensor exposure time in nanoseconds.
    u32 ir_leds;      ///< Controls the IR leds. All leds: 0, Bright group: 1, Dim group: 2, None: 3.
    u32 digital_gain; ///< IR sensor signal's digital gain.
    u8  negative;     ///< Inverts the captured image if 1.
    u8  pad[7];
    u32 sensor_res;   ///< IR Sensor resolution. 240x320: 0, 120x160: 1, 60x80: 2.
} irsImageTransferProcessorConfig;
```
```
/** 
 * Gets the default configuration for Image Transfer mode
 * Defaults are exposure 300us, IR LEDs all ON, 8x digital gain, normal image and resolution 240 x 320.
 */
void irsGetDefaultImageTransferProcessorConfig(irsImageTransferProcessorConfig *config);
```

**Comment by yellows8** [comment]
Yeah, except with "{value}: {description}".

"for Image Transfer mode" Period missing.

**Comment by CTCaer** [comment]
Fixed the period.
If the following is what you want, I'll push the commit
```
u64 exposure;     ///< IR Sensor exposure time in nanoseconds.
u32 ir_leds;      ///< Controls the IR leds. {0}: {All leds}, {1}: {Bright group}, {2}: {Dim group}, {3}: {None}.
u32 digital_gain; ///< IR sensor signal's digital gain.
u8  negative;     ///< Inverts the captured image. {0}: {Normal image}, {1}: {Negative image}
u8  pad[7];
u32 sensor_res;   ///< IR Sensor resolution. {0}: {240x320}, {1}: {120x160}, {2}: {60x80}.
```

**Comment by yellows8** [comment]
{} was not for the final text...

**Comment by CTCaer** [comment]
Done.

Never used doxygen before, so I thought it parses them if they are styled with { }: { }

**Comment by CTCaer** [comment]
Fun fact: The color inversion is actually happening inside the controller. That variable is passed through the x21 subcmd.

**Pull request merged**
