### PR TITLE
Gfx: Potential mitigation for docked mode

### PR DESCRIPTION
**Pull request by Cpasjuste**
This does mitigate the crashes in docked mode. It have been successful on multiple projects (pSNES, pFBA..). Not sure if it's the way to go but it does work. This have been found by m4xw when working on retroarch.

### CODE REVIEW

**Comment by fincs** [comment]
It looks like something went wrong and you added a bunch of extra commits rebased under your name. Could you cleanly rebase on top of latest master?

Also, right now I'm working on a complete overhaul of the gfx code.

**Comment by m4xw** [comment]
You could've at least cherry picked my commit instead just copying the code+commit message when creating a PR.
And as I said, I got told that this wont get accepted.

**Comment by yellows8** [comment]
Closing, see: https://github.com/switchbrew/libnx/pull/157#issuecomment-415979652

**Comment by Cpasjuste** [comment]
Well, i couldn't "cherry pick" your commit as i don't know how to do that (and wont bother to do so). You were "credited" for that, "at least".

**Comment by m4xw** [comment]
@Cpasjuste Its not about "credit", it's about breaking commit history.

**Pull request closed without merging**
