### PR TITLE
Fix unused parameter warnings in tipc.h when -Wextra is used.

### PR DESCRIPTION
**Pull request by DarkMatterCore**

### CODE REVIEW

**Comment by fincs** [comment]
Alternatively remove the unused parameters directly, that should be cleaner.

**Comment by DarkMatterCore** [comment]
> Alternatively remove the unused parameters directly, that should be cleaner.

@fincs That would require `tipcDispatchImpl` to be modified as well. Would you prefer to remove the `TipcService` argument from it, too? TIPC macros would have to be updated as well.

**Comment by fincs** [comment]
tipcDispatchImpl still needs the TipcService argument because it uses svcSendSyncRequest.

**Comment by DarkMatterCore** [comment]
@fincs Just removed the unused parameters altogether.

**Pull request merged**
